### ISSUE TITLE
Login authentication failing - "Logging in failed - check your credentials"

### ISSUE THREAD

**Issue by xspiduh** [j-andrews7/kenpompy#111]
## Description
The `login()` function is failing with the error "Logging in failed - check your credentials" despite valid credentials that work on kenpom.com directly. This appears to have started with the 2024-25 season updates to KenPom's website.

## Environment
- **Python version:** 3.13.2
- **kenpompy version:** 0.4.0
- **Operating System:** Windows 11
- **Installation method:** pip

## Dependencies
```
cloudscraper==1.2.71
requests==2.32.3
bs4==4.13.3
lxml==5.3.1
```

## Steps to Reproduce
1. Install kenpompy via pip
2. Attempt to login with valid credentials:
```python
from kenpompy.utils import login

KENPOM_EMAIL = "myemail@example.com"
KENPOM_PASSWORD = "mypassword"

browser = login(KENPOM_EMAIL, KENPOM_PASSWORD)
```
3. Error occurs immediately

## Expected Behavior
Login should succeed and return an authenticated CloudScraper browser session.

## Actual Behavior
```
Exception: Logging in failed - check your credentials
```

### Manual Login Test
- ✅ Credentials work when logging in directly at https://kenpom.com
- ✅ KenPom subscription is active
- ✅ Can access subscriber-only pages manually

### CloudScraper Test
Tested CloudScraper's ability to access KenPom:
```python
import cloudscraper
scraper = cloudscraper.create_scraper()
response = scraper.get("https://kenpom.com")
print(response.status_code)  # Returns: 200 ✅
```
CloudScraper successfully bypasses Cloudflare protection.

### Regular Requests Test
```python
import requests
response = requests.get("https://kenpom.com")
print(response.status_code)  # Returns: 403 ❌
```
Regular requests are blocked by Cloudflare (as expected).

## Analysis
- CloudScraper is successfully accessing KenPom (status 200)
- The issue appears to be with the login form submission itself, not Cloudflare blocking
- Likely caused by KenPom updating their login form/authentication before the 2024-25 season

## Additional Context
This was working perfectly 2-3 months ago (during the 2024-25 season). The timing suggests KenPom made changes to their authentication system for the new season.

## Potential Causes
1. Login form field names changed (e.g., `email` → `username`)
2. Additional CSRF tokens or hidden form fields required
3. Login endpoint URL changed
4. New authentication flow (cookies, sessions, etc.)

## Willing to Help
I'm a Master's student in Cybersecurity and would be happy to help debug this issue, test fixes, or contribute code if needed.

## Full Error Traceback
```
Traceback (most recent call last):
  File "CBBMODEL.py", line 24, in <module>
    browser = login(KENPOM_EMAIL, KENPOM_PASSWORD)
  File "C:\Users\itzsp\AppData\Local\Programs\Python\Python313\Lib\site-packages\kenpompy\utils.py", line 38, in login
    raise Exception('Logging in failed - check your credentials')
Exception: Logging in failed - check your credentials
```

## Workaround
Currently exploring manual CloudScraper implementation to bypass the broken login function while waiting for a fix.

**Comment by steveroks** [comment]
any updates on this? I tried commenting out that 'logout' detection and even changed the url to https://kenpom.com/account.php to check for 'logout' and it didnt make any difference. Thanks!

**Comment by j-andrews7** [comment]
v0.5.0 released on PyPi, which should fix this.

**Comment by steveroks** [comment]
im still getting the same error after updating to latest release

**Comment by j-andrews7** [comment]
I've been unable to replicate the issue on v0.5.0. If you've updated via `pip install --upgrade kenpompy` and are still getting the issue,  it'd be useful if you can run the first few bits of the [login function](https://github.com/j-andrews7/kenpompy/blob/master/kenpompy/utils.py#L8) to determine the response code, which should provide some hints about what's going on.

**Comment by steveroks** [comment]
response code is 200. 

looks like the table data is there but i dont see 'logged in as' anywhere in home_page.text

meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<style>
    .ui-tooltip {
        background: blue;
        color: white;
        padding: 2px;
        text-align:center;
        line-height: 1.2em;
    }
</style>

<LINK REL=stylesheet TYPE="text/css" HREF="css/rate2.css?1725252033">
<TITLE>2026 Pomeroy College Basketball Ratings</TITLE>


<script async src="https://www.googletagmanager.com/gtag/js?id=G-6DKK0E2CDM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-6DKK0E2CDM');
</script>


<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Signika:600,400&text=1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz:%c3%97%C3%A9%c2%b7%C2%A9%20%26%2B%2D%2C%2E%25%27%28%29%2a%7C%95%3F" />

<link rel="Shortcut Icon" type="image/ico" href="assets/favicon.ico?1662440188" />

<LINK REL=stylesheet TYPE='text/css' HREF='css/master2.css?1734893002'><script src='https://code.jquery.com/jquery-1.11.3.min.js'></script>
<script src='menu.js?1662440188'></script>

</head>

<body>
<div id="wrapper">
<div id="container">

<div id="logged-in">
<div id="login-box">
<div id='empty-left'></div><div id='login-form'><form id="login" method="POST" action="handlers/login_handler.php">
<input type="email" name="email" placeholder="E-mail"/ required>
<input type="password" name="password" placeholder="Password"/ required>
<input type="submit" name="submit" value="Login!" />
<span class="desktopHide"><br></span><input type="checkbox" name="remember" />Remember me &nbsp;&nbsp;
<a href="password_request.php">Forgot password?</a>
</form>
</div><div id="subscribe">
<span class="mobileHide"><a href="register-kenpom.php"><img src="assets/subscribe.png" alt="Subscribe!" /></a>
</span><span class="desktopHide subscribe_text"><a href="register-kenpom.php"><strong> SUBSCRIBE!</strong></a></span>
</div>
</div>
    
    <div id="logo-header">
        <div id="tagline-container">
            <div class="icon">
                <a href="https://doubletakeout.com"><img src="https://kenpom.com/assets/dt_logo.svg" width="30"></a>
                <a href="https://bballanalytics.com"><img src="https://kenpom.com/assets/bbanalytics.png" width="17"></a>
            </div>
            <div id="tagline"><h3>ADVANCED ANALYSIS OF COLLEGE BASKETBALL</h3></div>
            <div class="icon">
                <a href="https://kenpom.substack.com"><img src="https://kenpom.com/assets/substack.svg" height="16"></a>
                <a href="https://dunksandthrees.com"><img src="https://kenpom.com/assets/dunksandthrees.svg" height="16"></a>
            </div>
        </div>
        <hr><hr>
    </div> 
    <div id="nav2">
        <nav>
            <h1 class="logo"><a href="/"><img src="assets/kenpom_new.png" /></a></h1>
            <a class="burger-nav"><span class="burger-span">&#8801;</span></a>
            <ul id="main-menu">
                <li id="stats-menu" class="stats"><a href="#">Stats</a>
                    <ul>
                        <li><a href="summary.php">Efficiency</a></li>
                        <li><a href="stats.php">Four Factors</a></li>
                        <li><a href="playerstats.php">Player Stats</a></li>
                        <li><a href="pointdist.php">Point Distribution</a></li>
                        <li><a href="height.php">Height/Experience</a></li>
                        <li><a href="teamstats.php">Misc. Team Stats</a></li>
                    </ul>
                </li>
                <li class="fanmatch"><a href="fanmatch.php" title="FanMatch">FanMatch</a></li>
                <li class="universe"><a href="universe.php" title="D-I Universe">D-I Universe</a></li>
                <li id="misc-menu" class="misc"><a href="#">Miscellany</a>
                    <ul>
                        <li><a href="blog">Blog</a></li>
                        <li><a href="game_attrs.php">Game Rankings</a></li>
                        <li><a href="trends.php">D-I Stats Trends</a></li>
                        <li><a href="officials.php">Ref Ratings</a></li>
                        <li><a href="hca.php">Home Court Ratings</a></li>
                        <li><a href="arenas.php">Arena Capacity</a></li>
                    </ul>
                </li>
                <li class="search">
                    <form action="team.php">
                        <input id="teams" name="team" placeholder="Search teams"/>
                    </form>
                    <form action="history.php">
                        <input id="coaches" name="c" placeholder="Search coaches"/>
                    </form>
                </li>
                <li class="contact"><a href="contact.php" title="Contact">Contact</a></li>
            </ul>
        </nav>
    </div>
    <hr>
    <hr>
</div>


<div id="content-header">
<h2 class='lh075'>2026 Pomeroy <span class="mobileHide">College Basketball </span>Ratings</h2><span class="rank lh14"><a href="blog/ratings-methodology-update">help</a><div id="years-wrapper"><div id="years-container"><a href="/index.php?y=2002">02</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2003">03</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2004">04</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2005">05</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2006">06</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2007">07</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2008">08</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2009">09</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2010">10</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2011">11</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2012">12</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2013">13</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2014">14</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2015">15</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2016">16</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2017">17</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2018">18</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2019">19</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2020">20</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2021">21</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2022">22</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2023">23</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2024">24</a>&hairsp;&middot;&hairsp;<a href="/index.php?y=2025">25</a>&hairsp;&middot;&hairsp;26</div><div id="scrollLeft" class="scrollFadeLeft"></div><div id="scrollRight"></div></div><span class="update">Data through games of <a href="fanmatch.php?d=2025-11-03">Monday, November 3</a>
<span class='mobileHide'> (169 games)
</span></span></div> 
<div id="data-area">
<div id='table-wrapper'><table id='ratings-table'>
<thead><tr class="thead1"><th class="hard_left"></th><th class="next_left"></th><th colspan="3"></th><th class='divide' colspan='4'></th><th class='divide' colspan='2'></th><th class='divide' colspan='2'></th><th colspan='6'  class='divide'>Strength of Schedule</th>
<th colspan='2' class='divide'>NCSOS</th></tr>
<tr class='thead2'><th class='hard_left'><a href='/index.php'>Rk</a></th>
<th class="next_left" style="text-align:left"><a href="/index.php?s=TeamName">Team</a></th>
<th class='conf'>Conf</th>
<th class='wl'><a href="/index.php?s=Wins">W</a>-<a href="/index.php?s=Losses">L</a></th>
<th title="Adjusted efficiency margin" id='position1' class='column-sort'><a href="/index.php">NetRtg</a></th>
<th colspan=2 title="Adjusted offensive efficiency: points scored per 100 possessions (adjusted for opponent)" id="position1" class='divide'><a href="/index.php?s=RankAdjOE">ORtg</a></th>
<th colspan=2 title="Adjusted defensive efficiency: points allowed per 100 possessions (adjusted for opponent)" id="position1"><a href="/index.php?s=RankAdjDE">DRtg</a></th>
<th colspan=2 title="Adjusted tempo: possessions per 40 minutes (adjusted for opponent)" id="position1" class='divide'><a href="/index.php?s=RankAdjTempo">AdjT</a></th>
<th colspan=2 title="Luck rating" id="position1" class='divide'><a href="/index.php?s=RankLuck">Luck</a></th>
<th colspan=2 title="Strength of schedule rating" id="position1" class='divide'><a href="/index.php?s=RankSOS">NetRtg</a></th>
<th colspan=2 title="Average AdjOE of opposing offenses" id="position1"><a href="/index.php?s=RankSOSO">ORtg</a></th>
<th colspan=2 title="Average AdjDE of opposing defenses" id="position1"><a href="/index.php?s=RankSOSD">DRtg</a></th>
<th colspan=2 title="Non-conference strength of schedule rating" id="position1" class='divide'><a href="/index.php?s=RankNCSOS">NetRtg</a></th>
</tr></thead>
<tbody>
<tr>
<td class="hard_left">1</td><td class="next_left"><a href="team.php?team=Houston">Houston</a></td><td class='conf'><a href="conf.php?c=B12">B12</a></td><td class="wl">1-0</td><td>+29.56</td><td class="td-left divide">119.3</td><td class="td-right"><span class="seed">13</span></td><td class="td-left">89.7</td><td class="td-right"><span class="seed">1</span></td><td class="td-left divide">67.5</td><td class="td-right"><span class="seed">362</span></td><td class="td-left divide">+.000</td><td class="td-right"><span class="seed">1</span></td><td class="td-left divide">-14.46</td><td class="td-right"><span class="seed">174</span></td><td class="td-left">96.2</td><td class="td-right"><span class="seed">187</span></td><td class="td-left">110.7</td><td class="td-right"><span class="seed">147</span></td><td class="td-left divide">-14.46</td><td class="td-right"><span class="seed">174</span></td></tr>
<tr>
<td class="hard_left">2</td><td class="next_left"><a href="team.php?team=Purdue">Purdue</a></td><td class='conf'><a href="conf.php?c=B10">B10</a></td><td class="wl">0-0</td><td>+29.15</td><td class="td-left divide">125.6</td><td class="td-right"><span class="seed">1</span></td><td class="td-left">96.5</td><td class="td-right"><span class="seed">28</span></td><td class="td-left divide">70.0</td><td class="td-right"><span class="seed">305</span></td><td class="td-left divide">+.000</td><td class="td-right"><span class="seed">1</span></td><td class="td-left divide">-99.00</td><td class="td-right"><span class="seed">217</span></td><td class="td-left">0.0</td><td class="td-right"><span class="seed">217</span></td><td class="td-left">200.0</td><td class="td-right"><span class="seed">217</span></td><td class="td-left divide">-99.00</td><td class="td-right"><span class="seed">217</span></td></tr>
<tr>
<td class="hard_left">3</td><td class="next_left"><a href="team.php?team=Kentucky">Kentucky</a></td><td class='conf'><a href="conf.php?c=SEC">SEC</a></td><td class="wl">0-0</td><td>+28.95</td><td class="td-left divide">121.2</td><td class="td-right"><span class="seed">8</span></td><td class="td-left">92.3</td><td class="td-right"><span class="seed">4</span></td><td class="td-left divide">73.7</td><td class="td-right"><span class="seed">46</span></td><td class="td-left divide">+.000</td><td class="td-right"><span class="seed">1</span></td><td class="td-left divide">-99.00</td><td class="td-right"><span class="seed">217</span></td><td class="td-left">0.0</td><td class="td-right"><span class="seed">217</span></td><td class="td-left">200.0</td><td class="td-right"><span class="seed">217</span></td><td class="td-left divide">-99.00</td><td class="td-right"><span class="seed">217



errors out with:
Traceback (most recent call last):
  File "/home/user/PycharmProjects/SportsAnalytics/NCAAB/test_kp.py", line 75, in <module>
    browser = login(kp_email, kp_password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swika/PycharmProjects/SportsAnalytics/NCAAB/test_kp.py", line 44, in login
    raise Exception('Logging in failed - check your credentials')
Exception: Logging in failed - check your credentials

**Comment by j-andrews7** [comment]
Not sure why you wouldn't see it, can you post a screenshot of the index
page on login?

**Comment by steveroks** [comment]
sorry, i wasnt checking the response code of the post. looks like its cloudflare blocking it

403
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> kenpom.com</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

**Comment by j-andrews7** [comment]
Yeah, we've been chasing this off and on. Lots of requests can trigger it
as well.

Honestly not a ton we can do about it beyond the efforts we've already made
(switching to cloudscraper, various tweaks to requests, etc).

I welcome contributions to improve robustness, but I am unlikely to dig on
it much myself (as I can't replicate anyhow).

**Comment by steveroks** [comment]
i rewrote the login definition to use selenium instead and it works great...its below if you are interested

def login(username, password):
    # Returns an authenticated browser that can then be used to scrape pages that require authorization.

    # build Chrome browser object
    options = webdriver.ChromeOptions()
    options.add_argument("user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/")
    options.add_argument("--headless=new")

    s = Service(r'./chromedriver')
    browser = webdriver.Chrome(service=s, options=options)
    browser.get('https://kenpom.com/index.php')

    # Find and fill in login form
    email_field = browser.find_element(By.NAME, 'email')
    email_field.send_keys(username)
    password_field = browser.find_element(By.NAME, 'password')
    password_field.send_keys(password)
    login_button = browser.find_element(By.XPATH, '//input[@type="submit" and @value="Login!"]')
    login_button.click()
    time.sleep(5)  # wait for login to complete

    return browser
